name: p5.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Render
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run render
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: output/*.png
        if-no-files-found: error
    - name: Post to Minio
      uses: hkdobrev/minio-deploy-action@v1
      with:
        endpoint: ${{ secrets.MINIO_ENDPOINT }}
        access_key: ${{ secrets.MINIO_ACCESS_KEY }}
        secret_key: ${{ secrets.MINIO_SECRET_KEY }}
        bucket: 'p5js-action-test'
        # Optional inputs with their defaults:
        source_dir: 'output'
        target_dir: '/'
